version: '3'
services:
  optimisation:
    build:
      context: .
    volumes:
      - ./src:/app/src:ro
    container_name: optimisation
    ports:
      - "5000:5000"
    networks:
      - opt
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: 'samir5636123'
    # entrypoint: ['/opt/oracle/scripts/entrypoint.sh'] 
    volumes:
      - ./scripts/entrypoint.sh:/opt/oracle/scripts/entrypoint.sh
    networks:
      - opt
networks:
  opt:
  